### ISSUE TITLE
No Step 10

### ISSUE THREAD

**Issue by charliep51** [Lotterleben/AODVv2-Draft#30] opened 2016-07-01 15:03 UTC
In section 8.2.2.  RREP Reception, under step 5, there is an instruction "*  If not, continue to Step 10."  But there is no Step 10.

**Comment by Lotterleben** [comment] 2016-07-21 16:22
Would it make sense to change that line to "If not, ignore this RREP for further processing."?

**Comment by charliep51** [comment] 2016-07-21 16:58
I think the problem had to do with text that was misinterpreted to be a pandoc directive.

Then I started wondering whether it would be possible to attach symbolic names to numbered steps (or items in a numbered list).  Then I ran out of time.  But anyway I reckon the problem will go away when the text is recompiled.

**Comment by Lotterleben** [comment] 2016-07-21 17:04
I think this one is different than https://github.com/Lotterleben/AODVv2-Draft/issues/29  (which was fixed by https://github.com/Lotterleben/AODVv2-Draft/issues/29)... The text in this case seems more like something we forgot to change when rearranging the section at some point.

I wondered the same thing about symbolic names, it would make things so much easier! I'll ask Rick in case I see him at the Bits-n-Bites tonight.

**Comment by pv0** [comment] 2016-08-01 17:35
Looks like its meant to be step 6 instead of 10? When processing an RREP, if its for us, stop, otherwise, try to forward it.
5.  Check if the OrigPrefix matches an entry in the Router Client Set
    *  If so, no further processing is necessary.
    *  If not, continue to Step 10.
6.  Check if a valid (Active or Idle) or Unconfirmed LocalRoute exists to OrigPrefix
    *  If so, continue to RREP forwarding.
    *  If not, a Route Error message SHOULD be transmitted toward TargPrefix according to
       [](#RERR_gen) and the RREP SHOULD be discarded and not forwarded.

**Comment by Lotterleben** [comment] 2016-08-01 19:09
Oh. Right! I've created a PR to fix that, I hope you don't mind :)

**Closed** 2016-08-03 17:01 UTC
